export { default as GLogin } from './GLogin/index.vue';
export { default as GCalendar } from './GCalendar/index.vue';
export { default as GStock } from './GStock.vue';
export { default as GOrders } from './GOrders.vue';
export { default as GClients } from './GClients.vue';
export { default as GFeedbacks } from './GFeedbacks.vue';
export { default as GGroomers } from './GGroomers.vue';
export { default as GGroomerDetail } from './GGroomerDetail.vue';
export { default as GClientDetail } from './GClientDetail.vue';
