export { default as GCreateEventModalForm } from './GCreateEventModalForm.vue';
export { default as GCalendarEventMenu } from './GCalendarEventMenu.vue';
export { default as GRemoveBtn } from './GRemoveBtn.vue';
export { default as GCreateClientModalForm } from './GCreateClientModalForm.vue';
export { default as GCreateOrderModalForm } from './GCreateOrderModalForm.vue';
export { default as GCreateGroomerModalForm } from './GCreateGroomerModalForm.vue';
export { default as GColorSelector } from './GColorSelector.vue';
export { default as GGroomerServicesTable } from './GGroomerServicesTable.vue';
export { default as GGroomerOrdersTable } from './GGroomerOrdersTable.vue';
